# Requires dependencies python3.10, yapf, pip and xsdata[cli,lxml,soap]
python fix_file_errors.py
xsdata -r autogenerated/fixed/ --package noptis
xsdata autogenerated/fixed/ROI-FromPubTrans.xsd --package noptis
yapf -ir noptis
