from dataclasses import dataclass
from autogenerated.noptis.ptshared.xmlstream import (
    ErrorMessage,
    ErrorResponse as XmlstreamErrorResponse,
    Message as XmlstreamMessage,
    MessageBatch,
    Request as XmlstreamRequest,
    Response as XmlstreamResponse,
)

__NAMESPACE__ = 'http://www.pubtrans.com/PT/1.0'


@dataclass
class ErrorReport(ErrorMessage):
    pass


@dataclass
class ErrorResponse(XmlstreamErrorResponse):
    pass


@dataclass
class Message(XmlstreamMessage):
    pass


@dataclass
class Messages(MessageBatch):
    pass


@dataclass
class Report(XmlstreamMessage):
    pass


@dataclass
class Request(XmlstreamRequest):
    pass


@dataclass
class Response(XmlstreamResponse):
    pass
